backend:
  name: github
  repo: will-t-harris/move-with-madeline
  branch: develop

media_folder: static/img
public_folder: /img

collections:
  - label: Index Pages
    name: index-pages
    files:
      - file: "blog/index-pages/index.md"
        label: Landing Page
        name: index
        fields:
          - { label: Intro Title, name: intro-title, widget: string }
          - { label: Intro Content, name: intro-content, widget: markdown }
          - { label: Intro Image, name: intro-image, widget: image }
      - file: blog/index-pages/fitness.md
        label: Fitness Page
        name: fitness-index
        fields:
          - { label: Fitness Title, name: fitness-title, widget: string }
      - file: "blog/index-pages/travel.md"
        label: Travel Page
        name: travel-index
        fields:
          - { label: Travel Title, name: travel-title, widget: string }
      - file: "blog/index-pages/food.md"
        label: Food Page
        name: food-index
        fields:
          - { label: Food Title, name: food-title, widget: string }
      - file: "blog/index-pages/lifestyle.md"
        label: Lifestyle Page
        name: lifestyle-index
        fields:
          - { label: Lifestyle Title, name: lifestyle-title, widget: string }
      - file: "blog/index-pages/pcos.md"
        label: PCOS Page
        name: pcos-index
        fields:
          - { label: PCOS Title, name: pcos-title, widget: string }

  - label: Fitness Pages
    name: fitness
    folder: blog/fitness
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} -- {{year}}/{{month}}/{{day}}"
    create: true
    fields:
      - { label: Fitness Post Title, name: fitnessPostTitle, widget: string }
      - { label: Fitness Post Published Date, name: fitnessPostDate }
      # TODO GENERATE SLUGS IN NODE?
      - {
          label: Fitness Post Top Content,
          name: fitnessPostTopContent,
          widget: markdown,
        }
      - {
          label: Fitness Post Image,
          name: fitnessPostImage,
          widget: image,
          allow_multiple: false,
        }
      - {
          label: Fitness Post Content,
          name: body,
          widget: markdown,
          hint: This is the body of the fitness page. This editor supports both rich-text and markdown entries,
        }
